package com.romisspa.app.domain.usecase

data class SpaUseCases(
    val getServicios: GetServiciosUseCase,
    val addServicio: AddServicioUseCase,
    val updateServicio: UpdateServicioUseCase,
    val deleteServicio: DeleteServicioUseCase,
    val getCitas: GetCitasUseCase,
    val addCita: AddCitaUseCase,
    val deleteCita: DeleteCitaUseCase,
    val updateCitaStatus: UpdateCitaStatusUseCase,
    val getClientes: GetClientesUseCase,
    val addOrUpdateCliente: AddOrUpdateClienteUseCase,
    val getVentas: GetVentasUseCase,
    val addVenta: AddVentaUseCase,
    val getProductos: GetProductosUseCase,
    val addProducto: AddProductoUseCase,
    val updateProducto: UpdateProductoUseCase,
    val deleteProducto: DeleteProductoUseCase,
    val getEmpleados: GetEmpleadosUseCase,
    val addEmpleado: AddEmpleadoUseCase,
    val updateEmpleado: UpdateEmpleadoUseCase,
    val deleteEmpleado: DeleteEmpleadoUseCase,
    val descontarInsumos: DescontarInsumosUseCase,
    val getRutinasDiarias: GetRutinasDiariasUseCase,
    val addOrUpdateRutinaDiaria: AddOrUpdateRutinaDiariaUseCase,
    val deleteRutinaDiaria: DeleteRutinaDiariaUseCase,
    val getTareasEspeciales: GetTareasEspecialesUseCase,
    val addOrUpdateTareaEspecial: AddOrUpdateTareaEspecialUseCase,
    val deleteTareaEspecial: DeleteTareaEspecialUseCase
)
